### ISSUE TITLE
Packages its .git directory

### ISSUE THREAD

**Issue by mikelococo** [League-of-Foundry-Developers/codemirror-lib#2]
This module ships with a `/modules/_CodeMirror/.git/` directory that I assume is an error in the packaging script. Omitting the `.git` directory if it's not needed would reduce the size of the module and eliminate cruft.

**Comment by zeel01** [comment]
This should have been corrected in the latest release.

**Comment by mikelococo** [comment]
It has been, indeed. Sorry for the noise and thanks for your work on Foundry plugins.
