### ISSUE TITLE
[Bug?] When installing, module.json file does point to wrong es.json file

### ISSUE THREAD

**Issue by lozalojo** [League-of-Foundry-Developers/codemirror-lib#4]
When installing from module repo, module.json installed in my HDD contains:

```
        {
            "lang": "en",
            "name": "English",
            "path": "lang/en.json"
        },
        {
            "lang": "es",
            "name": "Español",
            "path": "langs/es.json"
        }
```

langs\es.json contains a typo, is lang\es.json

But the file module.json at the repo is right...

The file https://github.com/League-of-Foundry-Developers/codemirror-lib/releases/download/5.58.3-fvtt2/_CodeMirror.zip contains also the wrong module.json file

**Comment by zeel01** [comment]
Sorry about that, should be fixed now. There was a typo in the manifest, which I corrected, but I kept forgetting to push an actual update.

**Comment by lozalojo** [comment]
Thank you!
